### ISSUE TITLE
Develop UI/UX of the system app.

### ISSUE THREAD

**Issue by HealthTeam17** [HealthTeam17/Record-Health#10]
Start UI/UX design, and work with @naytdgreat to get a full overview of app design.
Reference :[]( https://drive.google.com/drive/folders/1qOevGW6kU2j8lsIjkhiQPxO15t1JgPGm)
Start Time: 14th Nov
End Time: 18th Nov
Work as a team on this

**Comment by Detective-Khalifah** [comment]
Roger. Have you worked with figma or a similar software before, @naytdgreat, @adetaj?

**Comment by naytdgreat** [comment]
No i haven't worked with figma before..

**Comment by naytdgreat** [comment]
@Detective-Khalifah have you?

**Comment by Detective-Khalifah** [comment]
How do we work things out?
We MIGHT need a collaborative tool
I only took a crash course when I needed to design an app

**Comment by adetaj** [comment]
Hi all,

I have not use figma before.

**Comment by naytdgreat** [comment]
Well give it a try... Just sample one of the designs suggested

**Comment by Detective-Khalifah** [comment]
I just confirmed from the team lead we're not designing, but writing code in our versions of the project/repo clone.
@adetaj
@naytdgreat

**Comment by naytdgreat** [comment]
We ought to have a ui design that we want to achieve in the code.

**Comment by Detective-Khalifah** [comment]
Guess so. Check Slack workspace.

**Comment by MUTINDAH** [comment]
@naytdgreat @Detective-Khalifah let us have a simple XML design using flow chart and design .then we will add modules and themes later

**Comment by naytdgreat** [comment]
Who will volunteer to do this ...

**Comment by MUTINDAH** [comment]
@naytdgreat @Detective-Khalifah Due to time is a bit limited, having a working UI(XML code) and modules,this will be easy to modify to our preferences

**Comment by MUTINDAH** [comment]
@naytdgreat AAD guys and cloud guys with kotlin coding experience can join

**Comment by naytdgreat** [comment]
Can Khalifah do that. I am not on the  Android track. Don't know how to do
that

**Comment by naytdgreat** [comment]
Let the AAD guys join please

**Comment by MUTINDAH** [comment]
@naytdgreat  I had told @Detective-Khalifah  to do so on slack , let him confirm if he can

**Comment by Detective-Khalifah** [comment]
I could do part of it, @MUTINDAH. Is @adetaj AAD?

**Comment by MUTINDAH** [comment]
@Detective-Khalifah Good, @adetaj yes is AAD pls find him we work on this urgently

**Comment by MUTINDAH** [comment]
I am also AAD guy but held up on team lead role. but can also help

**Comment by naytdgreat** [comment]
Alright

**Comment by MUTINDAH** [comment]
@Detective-Khalifah use jetpack libraries like compose,androidx  preferences will be faster to build UI

**Comment by UrieLight** [comment]
Hello,
Can't you build the Views and Layouts graphically ?
That will speed up the task.

**Comment by Detective-Khalifah** [comment]
Sure

**Comment by HealthTeam17** [comment]
@Detective-Khalifah @adetaj @UrieLight How far have we reached now? any support you require?
