### ISSUE TITLE
Create an Admin Patient's registration form

### ISSUE THREAD

**Issue by HealthTeam17** [HealthTeam17/Record-Health#14]
Create a simple layout with admin registration form

**Comment by Detective-Khalifah** [comment]
https://github.com/HealthTeam17/Record-Health/blob/dev_khalifah/app/src/main/java/com/healthteam17/recordhealth/AdminRegistrationFragment.kt
https://github.com/HealthTeam17/Record-Health/blob/dev_khalifah/app/src/main/java/com/healthteam17/recordhealth/PatientRegistrationFragment.kt
