### ISSUE TITLE
Merge changes in the develop branch to main branch for deployment

### ISSUE THREAD

**Issue by HealthTeam17** [HealthTeam17/Record-Health#17]
Cloud engineers work as a team to assist in merging of develop branch which has modifications to main branch.
Start: 22 Nov
End : 22 Nov

**Comment by UrieLight** [comment]
Hi,
I have no visibility on the evolutions.
Since 10 days, no push on repository.

I guess that the develop branch is only visible by the UI group.

Please provide some details.
Where shall we deploy the final app ?
What's the current development environment consist of ?

**Comment by HealthTeam17** [comment]
@UrieLight Main Branch has no modification pushed to it so far.
Modification are on develop branch, Changes needs to be merged into the Main branch.
Can't view develop branch? I added no restriction.

Deployment should be done on the Main branch.
Changes are made on develop branch, then after verification, it's merged onto Main branch
